language: node_js
node_js:
- 8.9.3
notifications:
  email:
    on_failure: change
    on_success: change
addons:
  ssh_known_hosts:
  - 167.99.39.206
branches:
  only:
  - master
env:
  global:
  - REMOTE_APP_DIR=/home/deploy/hdate
  - REMOTE_USER=deploy
  - REMOTE_HOST=167.99.39.206
  - PORT=8080
before_install:
- openssl aes-256-cbc -K $encrypted_e743e2d84c63_key -iv $encrypted_e743e2d84c63_iv
  -in deploy.enc -out deploy -d
install:
- npm install
before_script:
- chmod 600 deploy && mv deploy ~/.ssh/id_rsa
script:
- npm run build-prod
after_success:
- bash ./scripts/deploy.sh
