sudo: required
language: node_js
node_js:
- 8.9.4
notifications:
  email:
    on_failure: change

jobs:
  include:
    - stage: lint
      install:
      - npm install
      script:
      - yarn lint
    - stage: build
      install:
      - npm install
      script:
      - yarn build-prod
    - stage: deploy
      env:
      - DEPLOY_HOST=https://captain.captain.jonahmeijers.nl
      - DEPLOY_NAME=date
      - DEPLOY_BRANCH=master
      install:
      - yarn global add captainduckduck
      script:
      - captainduckduck deploy -s -h $DEPLOY_HOST -a $DEPLOY_NAME -p $DEPLOY_PASS -b $DEPLOY_BRANCH

stages:
  - lint
  - build
  - name: deploy
    if: branch = master