language: node_js
node_js:
- 8.9.3
notifications:
  email:
    on_failure: change
    on_success: change
addons:
  ssh_known_hosts:
  - 167.99.39.206
branches:
  only:
  - master
env:
  global:
  - REMOTE_APP_DIR=/var/www/MY_DOMAIN.COM/
  - REMOTE_USER=deploy
  - REMOTE_HOST=167.99.39.206
  - PORT=8080
before_install:
- openssl aes-256-cbc -K $encrypted_e743e2d84c63_key -iv $encrypted_e743e2d84c63_iv
  -in deploy.enc -out deploy -d
- npm install -g npm@^2
install:
- npm install --only=dev
before_script:
- chmod 600 deploy && mv deploy ~/.ssh/id_rsa
script:
- npm run build
after_success:
- "./scripts/deploy.sh"
