language: node_js
node_js:
- 8.9.4
notifications:
  email:
    on_failure: change
branches:
  only:
  - master
before_install:
  - sudo apt-get install .gyp python make g++

jobs:
  include:
    - stage: lint JS
      install:
      - npm install
      script:
      - npm run lint
    - stage: build assets
      install:
      - npm install
      script:
      - npm run build-prod
    - stage: deploy to captainduckduck
      env:
      - DEPLOY_HOST=https://captain.captain.jonahmeijers.nl
      - DEPLOY_NAME=date
      - DEPLOY_BRANCH=master
      install:
      - npm install -g captainduckduck
      script:
      - captainduckduck deploy -s -h $DEPLOY_HOST -a $DEPLOY_NAME -p $DEPLOY_PASS -b $DEPLOY_BRANCH